### PR TITLE
Proposal: Optional, config-driven upgrade modes for reactors, radiators and generators.

### PR DESCRIPTION
**Pull request by chwthewke**
What’s this?

My goal was to modestly increase the configurability of KSPIL, and more precisely the electrical subsystem. Thus, apart from slight cosmetic changes (improvements I hope) and miscellaneous bugs I came across, this pull request does not change the behaviour of KSPIL until you modify some part configs.

What this does is re-introduce the “upgrade part with later tech” mechanism for all nuclear reactors, heat radiators and the electric generator, but in an optional way that relies on part configs only, works with TweakScale, and is not activated by configs in this PR (my “upgrade-configs” branch has some configs I made that activate upgrades if you would like to have a look; right now they are part configs and I plan to make them MM patches). The "Retrofit" action stays gone as well, and ship parts will stay as upgraded as they were at the time they launched.

Basically, I’ve introduced a new module `FNUpgradeModule` that, when added to a part is in charge of calling into its sibling `FNUpgradeableModule`s to do the upgrade stuff. It is not added to the part configs by default, and when added (after the TweakScale module), it gets scaled values and everything works nicely with e.g. rescaled reactors.

Details:
- The `FNUpgradeableModule` interface was modified, and `hasTechRequiredForUpgrade` was deduplicated between modules into an extension method.
- The new (and not used by default) `FNUpgradeModule` takes care of discovering, enabling and persisting upgrades for upgradeable modules.
- Refactored (deduplicated) `GetInfo()` for reactors, also, `GetInfo()` displays upgraded values, only if upgrades are enabled.
- Likewise, `GetInfo()` for radiators no longer displays values for temperatures above the unupgraded max temperature (by default 2000°K), unless upgrades are enabled.
- Fixed a likely bug in `FNFusionReactor` where the reactor would attempt to produce Charged Particles, resulting in reduced output.
- Added a display of the part variant in the Part UI for generators and radiators (where it was missing), only when upgrades are added.
- Added the Core Temperature and Power Output to reactors in the Editor scene, whether upgrades were added or not. It reacts correctly to scale changes and I figured it could be useful to know those numbers in the editor even when not using upgrades.
- Misc: The Thermal Rocket Nozzle/Turbojet computes its ISP correctly as soon as it is activated (thus avoiding erroneous delta-v values in MechJeb between loading the ship and actually thrusting with the TRN).
- Micro-bug in `FNRadiator`: Convected power was not correctly updated when rapidly leaving the atmosphere (such as when using HyperEdit to jump into orbit during testing).
- Known issue (or is it?): Ships that were built unupgraded, when launched directly from the launchpad without hitting the VAB after acquiring the upgrade are not upgraded; going through the VAB upgrades them. (I'm not sure how it worked in 0.11)

Please let me know if you would consider merging this PR, or if there is anything more (or less) I can change to make it mergeable. In particular, I’ve been much less aggressive at cleaning up unused code and de-duplicating stuff than I usually am, in the interest of limiting the quantity of modified lines here. If you’d like me to do more of that, I will, gladly. Also, I’ve left a few debugging “print”s inside “#if DEBUG/#endif” pragmas, if that bothers you, say the word and they’re gone.

Thanks for reading all this, and thanks again for your work on KSPI which is an outstanding mod!

### CODE REVIEW

**Comment by confusingbits** [comment]
This is interesting. I do want to add part upgrade support for kspil, but I want to do it in an way that is tree agnostic to allow players to use whatever tree they want to download. My napkin plan right now is to use currency instead of tech nodes. So instead of a certain node to unlock all parts upgraded, you'd need to invest a combination of rare resources, funds and science to unlock an upgraded version. All of which are part configurable.

If you'd like to iterate on that with a working design, I'd be happy to try it. Keep in mind, it is just an idea. Playtesting will determine if it is a good idea or not.

I am also playing with the idea that the science lab and appropriate currencies and and an eva kerbal are required to retrofit existing parts. So you could have full fledge retrofit missions, which could be extended later with some actual gameplay/minigames involved, instead of just a right click menu. (This is farther down the down the road.) But it something to keep in mind.

I don't mind you cleaning up and reorganizing the code you are working on so long as it is clear, concise and copiously commented. Fractal style is very hard for me to follow anyway.

Please submit you code to the development branch, the master branch is for the current release.

**Comment by chwthewke** [comment]
I think I like your plan, and I'd definitely like to give it a try. As for this master vs. development branch thing, I'm totally blaming the github UI because my branch is based on development and I selected it and never realised the PR was against master :|. Anyway I'll open a new PR once I've got something.

**Comment by chwthewke** [comment]
So, I’ve been giving some thought to game design ideas for unlockable part upgrades and retrofitting missions.

About retrofit missions, the thing is that they would have to be balanced against simply replacing the entire ship (in the case of a very large ship, it’s very likely that docking is involved and the new part can be swapped in or just added via docking), which I think limits the scope of such missions, as acquiring even say one million funds never seems to take very long unless one adheres to strict roleplaying guidelines. 

Nevertheless, I don’t think this is all bad as, first, it does not completely preclude these missions, and second, it frees up some design space for “upgrade research” missions, which would have no alternative to compete against and could be quite elaborate (hopefully without becoming outright unreasonable).

With that argument in mind, I looked at the “combination of rare resources, funds and science”. Here I'll admit I’m a bit stumped by the resources bit: using existing resources looks unadvisable, as they can be stocked in the VAB and even requiring newly-extracted resources seems pretty difficult to express in the game (and, relatedly, rather complicated to program I would think). New, dedicated resources, on the other hand, I fear would be kind of weak if they supported only that little part of the progression in the game. 

However, the premise of requiring space missions to unlock upgrades brought me to think of some modded contracts I’ve played in FinePrint, and I believe something fun could be done with location-based requirements; for example:
- The part can be researched by Kerbals on the ship (probably requiring a lab, as well as the part), without any location constraint (or maybe rather, anywhere in space, because Launchpad research is a “meh” kind of requirement). 
- This would cost funds and science, why not also time. 
- After that, the Kerbals report that the part needs to be tested in a specific, random situation such as “in orbit”, “landed at” or even “landed near a certain point” on a given body. I’d add that the difficulty of reaching that place should be tied to the tier of the part being researched. 
- At this point, the player could either depart and perform the research at the prescribed location or reset the experiment for a re-roll of the second objective (thus incurring the cost of the first step once again).
- The research trip could have more than two steps for higher tier parts, although that may be overkill as well as not too easy to achieve.
- It could be allowed to perform the different steps on different instances of the part, but I don't really favor that, as single-ship missions would likely be shorter and more intense.
- All of this should not be technically tied to the contracts system, because it needs to work in Science Sandbox mode. On the other hand, some additional requirements regarding part tests could be added in career mode (not too enthusiastic about that though given the randomness of contract offers).

What do you think?

PS: I've re-opened this PR not because I think anything should be merged, but to ensure you get a notification - not sure how github works in this regard. No hurry though :)

Cheers

**Comment by confusingbits** [comment]
I didn't mean to send you off to try and build an upgrade mission system. I'd need to write design doc for that.

What I meant to was that functionality should be as non-specific possible. For instance, fractal wrote the reactor class and then inherited reactors to make all of the different types. He should have just made the reactors and designed the inputs and outputs and all the various bits and pieces into a generic reactor module that is defined into specific reactors in the part config.

The hardcoded all the generator modes, when he could have defined them in the config.

Things like that.

In either case, the focus of this next major release is resources, which haven't been fully iterated on yet, and exposing more part functionality to the config. The part config stuff doesn't need to be done overnight and is mostly feedback driven. I don't expect to do another major release for a month or two. So, I am still very much in the gather feedback from last update and toss around neat ideas phase.

**Comment by confusingbits** [comment]
I'd like to continue this discussion, some of your ideas sound fun, but I'd rather do it on the forum though. Feel free to quote the discussion here.

**Comment by chwthewke** [comment]
Alright, I'll be replying in the forums, thanks.

**Pull request closed without merging**
