### PR TITLE
Do not consume megajoules if the refinery process is has no input materi...

### PR DESCRIPTION
**Pull request by jakkarth**
...al or room for output material.

When the reactor/generator attached to the refinery is undersized, the processes shouldn't stop, but rather should slow down. There's no sense in burning electricity trying to electrolyse alumina if we don't have any, or if the storage for the aluminum and oxidizer is full. This patch is intended to address this issue by refunding the consumed megajoules if it turns out we can't complete the conversion.

It's untested, as I have no idea how to compile KSP mods. Feedback welcome.

### CODE REVIEW

**Comment by jakkarth** [comment]
I'm not sure this is a 100% fix for the issue either. I didn't see anything in the refinery about mining, so if that's processed first and it uses up all the megajoules for the tick, then there will be 0 for the refining and the patch will be ineffective at preventing the deadlock.

**Comment by jakkarth** [comment]
And now a companion fix for the ORS mining side of things. I'm not sure if this is compatible with ORS 1.1.0 or whatever the independent version is. I'm guessing given the references fo consumeFNResource that this is an interstellar-specific fork of ORS, so I'm not going to try to submit this patch to them as well.

**Comment by confusingbits** [comment]
Sorry, I'm not the best at git, but can you fork from development and then submit a pull request?

**Comment by jakkarth** [comment]
I can, yes. It looked as though development was behind master by 187 commits, which is why I chose master to base my changes on. I'll have it up shortly. Thanks!

**Pull request closed without merging**
