### PR TITLE
Development

### PR DESCRIPTION
**Pull request by mellon85**
Added red-color effect to radiators. The glow texture has been made a little bit more red to increase the multiplicative effect of the KSP shader.

Not enabled on inline, radial or large flat radiators as they don't have the proper shader nor textures.

I have tested it on inline radiators, but the effect is not as good as the radiators. I will try, when i get how to load a texture from the code, to add the glow effect the radial radiators.

### CODE REVIEW

**Comment by mellon85** [comment]
a better one is coming with support for everything (except inline)

**Comment by Olympic1** [comment]
Why should you make it look like it's hotter when in the real world you never see it glow in space.

**Comment by mellon85** [comment]
metals heat at 1500K emit no radiations in the spectrum visible by the human eye?

**Comment by Olympic1** [comment]
True, because it only emits in infrared (and visible light like the sun) but you can only see it with a infrared camera.

**Comment by mellon85** [comment]
ok, then I'll close the other one :)

**Comment by confusingbits** [comment]
The metal and carbon radiators are indeed visible. Not that it matters much. It would be good to have a visual indication of waste heat build up on the vessel with the radiators. Assuming you can add support for all the radiators in a consistent manner, and that it looks good, I would be glad to support this feature.

PS. Don't let the realism nerds stop you. They wouldn't be playing ksp if someone didn't decide to force them to have some fun every once in a while.

**Comment by Olympic1** [comment]
Yea, but this nerd has a internship by EA

**Comment by confusingbits** [comment]
And I'm a published physicist.

Calm down. It wasn't an insult. :)

**Comment by Olympic1** [comment]
ah ok, but the internship is true

**Comment by confusingbits** [comment]
I didn't doubt it. Congrats.

**Comment by mellon85** [comment]
I write software for airplanes.. Andin that spirit I would say that in case
we can make it configurable from the plugin's settings for strict realism
or not. Anyway ignore this pull request, the #10 is more complete.
Il 09/ago/2014 22:58 "WaveFunctionP" notifications@github.com ha scritto:

**Comment by confusingbits** [comment]
Very well, closing.

**Pull request closed without merging**
