### PR TITLE
Refund unused resources if refining/mining cannot be completed.

### PR DESCRIPTION
**Pull request by jakkarth**
Fixes some inequality bugs introduced by the first attempt, and refunds all of the unused resources instead of just the megajoules. Also updates the appropriate status display variables.

### CODE REVIEW

**Comment by jakkarth** [comment]
Sorry to ask once again, but any eta on a dev build? I've tried for the past hour to get monodevelop to open the kspi project, but it chokes on the csproj files. Brief instructions on how to compile without unity (or a link thereto) would be much appreciated as well. Thanks!

**Comment by confusingbits** [comment]
I'm not familiar with monodevelop, you can get vs for free which should handle it just fine.

**Comment by jakkarth** [comment]
Sadly, Visual Studio doesn't run on Linux, and I don't have access to a legal copy of Windows.

**Comment by confusingbits** [comment]
a google search turned up this:

http://stackoverflow.com/questions/9220290/open-a-csproj-with-monodevelop

**Comment by jakkarth** [comment]
I saw that one and many other pages. I'm getting errors about extern alias ORSv1_1 was not specified in -reference option, even though I've added the appropriate source files for the project to build it AND added the precompiled orsv1_1_0 dll from your dev build. I am not familiar enough with C# development to have any idea what to do about it, and my patience in reading google search results and trying to fiddle with monodevelop has reached its end for the day. Looks like I'll waiting on your dev build. Thanks for the help.

**Comment by confusingbits** [comment]
On the references for ORS, look at the properies. you'll find a field called alias. It says global usualy, it should say global, ORSv1_1

**Comment by confusingbits** [comment]
basicly, add the ors dll as a reference, and then click on the ors reference and add ORSv1_1 as an alias

**Comment by jakkarth** [comment]
I understand that that's what I need to do, and I see a lot of tutorials about how to do it with VS, but as far as I can tell there's no way to add an alias for a reference within monodevelop. There's no context menu options in the solution explorer, and inside the Edit References window all I can do is add and remove, nothing more.

**Comment by jakkarth** [comment]
Yeah, this pull request is completely braindamaged. I managed to get a copy of windows 7 from work and install visual studio c# 2010 on it, so now I can actually do my own builds and tests. I'm making progress but it's definitely not ready.

**Pull request merged**
